spring:
  application:
    name: csms

  datasource:
    url: jdbc:mysql://localhost:3306/ultratech?useSSL=false&serverTimezone=UTC
    username: root
    password: 451070
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false
    baseline-on-migrate: true
    # locations default to classpath:db/migration where our V1__...sql is placed


server:
  port: 8080

  servlet:
    session:
      timeout: 30m

# Enable debug logging for security & app to help diagnose authentication issues (development only)
logging:
  level:
    org.springframework.security: DEBUG
    org.computerspareparts.csms: DEBUG
    org.flywaydb: DEBUG
